[package]
name = "analytics-system"
version = "0.1.0"
edition = "2021"
default-run = "analytics-system"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.9"
duckdb = { version = "1.1.1", features = ["bundled"] }
